# General config
spring.main.banner-mode=off
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#logging.level.org.springframework.web=DEBUG
server.port=${PORT:8081}
server.servlet.context-path=/taniwha


central.backend.url=http://localhost:8088/taniwha
spring.profiles.active=default
node.ip=${NODE_IP}

# Node config
name=${NAME:unnamed}
desc=${DESC:no description available}
node.color=${COLOR:}
heartbeat.interval.ms=60000
retry.backoff.period.ms=2000
retry.max.attempts=3

# Security config
spring.security.user.name=cf9e0aac7c1054a748b7d618a6a2b6af
jwt.secret=secret_key
jwt.expiration=3600

# Kerberos config
kerberos.ticket.version=5
kerberos.realm=TANIWHA-REALM

# Logger config
logging.config=classpath:logback.xml
logging.level.org.taniwha=DEBUG
