# General config
spring.main.banner-mode=off
spring.profiles.active=default
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.path=${APP_PATH:/taniwha}
server.port=${PORT:8080}
server.servlet.context-path=/taniwha
spring.mvc.async.request-timeout=300000
server.tomcat.connection-timeout=300000
# Central service location
# Deployment
host.url=https://semantics.inf.um.es
host.service=/taniwha-ws
# Development
# host.url=http://localhost:8092
# host.service=/taniwha
# Node config
node.ip=${NODE_IP:8080}
name=${NAME:unnamed}
desc=${DESC:no description available}
node.color=${COLOR:#FF0000}
heartbeat.interval.ms=60000
retry.backoff.period.ms=2000
retry.max.attempts=3
# Security config
spring.security.user.name=${SPRING_SECURITY_USER_NAME:default}
jwt.secret=${JWT_SECRET:default}
jwt.expiration=10800
# Kerberos config
kerberos.ticket.version=5
kerberos.realm=TANIWHA-REALM
# Logger config
logging.config=classpath:logback.xml
logging.level.org.taniwha=DEBUG

tls.probe.enabled=true
# tls.probe.host=semantics.inf.um.es
# tls.probe.port=443
